<a href="https://colab.research.google.com/github/JrmDark/Intro-to-Numerical-Methods/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix and its Operations


In [9]:
import numpy as np
a = np.array([1,2,3]) #This is a 1x3 array
a[0] = 4
print(a)

[4 2 3]


In [10]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]]) #This is an example 2x3 matrix
b[0,0] = 7
print(b)


[[7 2 3]
 [4 5 6]]


In [11]:
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]]) #This is an example of square matrix
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
import numpy as np
d = np.full((2,2),4)
print(d)

[[4 4]
 [4 4]]


In [13]:
import numpy as np
e = np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


In [14]:
import numpy as np
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)


[1 5 9]


In [15]:
import numpy as np
f = np.empty((0,10))
print(f)

[]


In [16]:
import numpy as np
g = np.zeros((2,2))
print(g)

[[0. 0.]
 [0. 0.]]


In [24]:
import numpy as np
e = np.eye(2)
g = np.zeros((2,2))
print(e)
print(g)
print(e+g) #This is the code to get the summation of  matrices e and g
print(e-g) #This is the code to get the difference of  matrices e and g
print(g-e)

[[1. 0.]
 [0. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
