<a href="https://colab.research.google.com/github/JrmDark/Intro-to-Numerical-Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix and Its Operations


In [16]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A)
print(B)
sum = A+B
print(sum)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
[[ 1 -3]
 [ 6  4]]


In [17]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A)
print(B)
difference1 = B-A
print(difference1)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
[[11 -3]
 [-2  2]]


In [19]:
import numpy as np
A = np.array([[-5,0],[4,1]])
B = np.array([[6,-3],[2,3]])
print(A)
print(B)
difference2 = A-B
print(difference2)

[[-5  0]
 [ 4  1]]
[[ 6 -3]
 [ 2  3]]
[[-11   3]
 [  2  -2]]
